### ISSUE TITLE
GraphQL.ExecutionError: Invalid 'Content-Type' header: non-supported media type

### ISSUE THREAD

**Issue by Dustb0** [JannikLassahn/graphql-dotnet-upload#21]
Not sure this is a problem of graphql-dotnet-upload or graphql-dotnet (4.5.0) - but any help or pointers towards solving this issue would be greatly appreciated. 

GraphQL seems to no longer acceppt any multipart/form-data requests. I've tried it with your cUrl example from the Readme.md:
`{
  "errors": [
    {
      "message": "GraphQL.ExecutionError: Invalid 'Content-Type' header: non-supported media type. Must be of 'application/json', 'application/graphql' or 'application/x-www-form-urlencoded'. See: http://graphql.org/learn/serving-over-http/."
    }
  ]
}`

**Comment by JannikLassahn** [comment]
In most cases this error message is caused by the wrong middleware order. Please make sure that you call `UseGraphQLUpload` **before** `UseGraphQL`. 
I just tested the curl command with the sample project thats included in this repo and it worked fine.

**Comment by Dustb0** [comment]
Thank you so much for your quick response! Indeed that was the issue :)
