### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by ganhammar** [JannikLassahn/graphql-dotnet-upload#25]
Hi,

Sorry to be blunt but, since I depend on this package, is the project dead? :)

**Comment by JannikLassahn** [comment]
No worries, I appreciate your initiative! 
Once I'm back from vacation (in a few days) I'll make sure to review PRs.

**Comment by ganhammar** [comment]
Ah, great, thanks! Have a great reminder of your vacation!
