### ISSUE TITLE
How would I test a request in Graphiql?

### ISSUE THREAD

**Issue by itsdanieldk** [JannikLassahn/graphql-dotnet-upload#5]
Greetings, and thank you for this package. 

I'm developing an application where users need to be able to upload a profile picture, so I basically need upload/download functionality of images. I'm using asp.net core with graphql.

I'm trying to get my API to work with the package. I would like to be able to test it with graphiql, how would I go about making a request in graphiql with a file, etc?

Thank you.

**Comment by JannikLassahn** [comment]
I'm afraid GraphiQL doesn't support files right now. 
There are some clients listed in the [spec repo](https://github.com/jaydenseric/graphql-multipart-request-spec#client) that support the file upload spec. [Altair ](https://github.com/imolorhe/altair)seems quite good, but i haven't tested this client yet.
Of course, if you prefer GraphiQL you could fork it and try to implement the required parts yourself.
I hope this helps a bit.

**Comment by itsdanieldk** [comment]
Thanks for the information. I guess I'll leave graphql out of this then. :)

**Comment by JannikLassahn** [comment]
For @iyyel and anyone interested in testing file uploads specifically with GraphiQL:
I built the most basic custom version of GraphiQL that supports files. To test it use the _graphiql-file-upload_ branch, start the sample application and navigate to _localhost:5000/GraphiQL.html_.

![graphiql](https://user-images.githubusercontent.com/18314036/68166653-4a01fc00-ff63-11e9-8bb2-b204053b4303.PNG)

This is just a little experiment, so don't expect too much ;)
