### ISSUE TITLE
Pass files to IDocumentExecuter

### ISSUE THREAD

**Issue by gfawkes09** [JannikLassahn/graphql-dotnet-upload#8]
Hi, this library is quite nifty. Thanks.
I am using graphql-dotnet, and while uploading the files, I would like to know how to create a new ExecutionOptions and pass the form files to the IDocumentExecuter from the operation/map objects in a web api controller.
Apologies as I am still quite new to graphql programming.

**Comment by JannikLassahn** [comment]
I don't quite understand, could you please elaborate on what you're trying to solve?

**Comment by iTobby** [comment]
Thanks for your response.
A typical graphql endpoint looks like the code below, but I can't seem to figure out how to pass a multipart request to the document executer via the execution options object.
```
public async Task<IActionResult> Post([FromBody] GraphQLQuery query)
{
      var inputs = query.Variables.ToInputs();
      var executionOptions = new ExecutionOptions
       {
           Schema = _schema,
           Query = query.Query,
           Inputs = inputs
       };
       var result = await _documentExecuter.ExecuteAsync(executionOptions).ConfigureAwait(false);
       return Ok(result);
}
```

**Comment by gfawkes09** [comment]
Thanks for your response.
A typical graphql endpoint looks like the code below, but I can't seem to figure out how to pass a multipart request to the document executer via the execution options object.
```
public async Task<IActionResult> Post([FromBody] GraphQLQuery query)
{
      var inputs = query.Variables.ToInputs();
      var executionOptions = new ExecutionOptions
       {
           Schema = _schema,
           Query = query.Query,
           Inputs = inputs
       };
       var result = await _documentExecuter.ExecuteAsync(executionOptions).ConfigureAwait(false);
       return Ok(result);
}
```

**Comment by JannikLassahn** [comment]
I see. Since this library is implemented as middleware, you cannot use it in combination with a typical controller. Do you really need that controller? If not, you could use the same setup as demonstrated in the [sample server](https://github.com/JannikLassahn/graphql-dotnet-upload/tree/master/samples/FileUploadSample).

**Comment by gfawkes09** [comment]
Oh I see. I'd give it a try without the controller then. Thanks

**Comment by JannikLassahn** [comment]
Feel free to reopen the issue if you have further questions.

**Comment by gfawkes09** [comment]
I was able to re-use some part of the middleware to parse the request and send the files via the controller successfully. Thanks
